import {type Metadata} from 'next'
import {
    ClerkProvider,
} from '@clerk/nextjs'
import {
    dark
} from "@clerk/themes";
import { Toaster } from "sonner";
import {Geist, Geist_Mono} from 'next/font/google'
import './globals.css'

import {ThemeProvider} from "@/components/theme-provider";

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider
            appearance={{theme: dark}}
            afterSignOutUrl="/"
        >
            <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <ThemeProvider
                attribute="class"
                forcedTheme="dark"
                storageKey="gamehub-theme"
            >
                <Toaster
                    theme="light"
                    position="bottom-center"
                />
                {children}
            </ThemeProvider>
            </body>
            </html>
        </ClerkProvider>
    )
}